from .position import Position

A1 = Position("A1")
A2 = Position("A2")
A3 = Position("A3")
A4 = Position("A4")
A5 = Position("A5")
A6 = Position("A6")
A7 = Position("A7")
A8 = Position("A8")

B1 = Position("B1")
B2 = Position("B2")
B3 = Position("B3")
B4 = Position("B4")
B5 = Position("B5")
B6 = Position("B6")
B7 = Position("B7")
B8 = Position("B8")

C1 = Position("C1")
C2 = Position("C2")
C3 = Position("C3")
C4 = Position("C4")
C5 = Position("C5")
C6 = Position("C6")
C7 = Position("C7")
C8 = Position("C8")

D1 = Position("D1")
D2 = Position("D2")
D3 = Position("D3")
D4 = Position("D4")
D5 = Position("D5")
D6 = Position("D6")
D7 = Position("D7")
D8 = Position("D8")

E1 = Position("E1")
E2 = Position("E2")
E3 = Position("E3")
E4 = Position("E4")
E5 = Position("E5")
E6 = Position("E6")
E7 = Position("E7")
E8 = Position("E8")

F1 = Position("F1")
F2 = Position("F2")
F3 = Position("F3")
F4 = Position("F4")
F5 = Position("F5")
F6 = Position("F6")
F7 = Position("F7")
F8 = Position("F8")

G1 = Position("G1")
G2 = Position("G2")
G3 = Position("G3")
G4 = Position("G4")
G5 = Position("G5")
G6 = Position("G6")
G7 = Position("G7")
G8 = Position("G8")

H1 = Position("H1")
H2 = Position("H2")
H3 = Position("H3")
H4 = Position("H4")
H5 = Position("H5")
H6 = Position("H6")
H7 = Position("H7")
H8 = Position("H8")
