# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt6 UI code generator 6.0.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets
from const import PieceLabels


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(730, 900)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(20, 20, 692, 848))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")

        for i in range(8, 0, -1):
            for char in range(ord("A"), ord("I")):
                temp_vertical_layout = QtWidgets.QVBoxLayout()
                temp_vertical_layout.setObjectName(f"verticalLayout_{chr(char)}{i}")

                temp_label = QtWidgets.QLabel(self.gridLayoutWidget)
                temp_label.setPixmap(QtGui.QPixmap("../img/white_king.png"))
                temp_label.setObjectName(f"label_{chr(char)}{i}")
                temp_vertical_layout.addWidget(temp_label)

                temp_comboBox = QtWidgets.QComboBox(self.gridLayoutWidget)
                temp_comboBox.setObjectName(f"comboBox_{chr(char)}{i}")
                
                for _ in range(7):
                    temp_comboBox.addItem("")

                temp_vertical_layout.addWidget(temp_comboBox)
                self.gridLayout.addLayout(temp_vertical_layout, i-1, char-65, 1, 1)

        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 822, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))

        for i in range(len(children := self.gridLayoutWidget.children())):
            widget = children[i] if isinstance(children[i], QtWidgets.QComboBox) else None
            if widget:
                for piece in PieceLabels:
                    widget.setItemText(piece.value, _translate("MainWindow", f"{piece.value} - {piece.name}"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
