# Form implementation generated from reading ui file 'C:\Users\Mski\Desktop\ChessEye\UI\main_window_test.ui'
#
# Created by: PyQt6 UI code generator 6.0.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(977, 918)
        self.main_widget = QtWidgets.QWidget(MainWindow)
        self.main_widget.setObjectName("main_widget")
        self.gridLayoutWidget_2 = QtWidgets.QWidget(self.main_widget)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(760, 20, 160, 81))
        self.gridLayoutWidget_2.setObjectName("gridLayoutWidget_2")
        self.piece_picker = QtWidgets.QGridLayout(self.gridLayoutWidget_2)
        self.piece_picker.setContentsMargins(0, 0, 0, 0)
        self.piece_picker.setObjectName("piece_picker")
        self.white_king = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.white_king.setText("")
        self.white_king.setPixmap(QtGui.QPixmap("C:\\Users\\Mski\\Desktop\\ChessEye\\UI\\img/white_king.png"))
        self.white_king.setObjectName("white_king")
        self.piece_picker.addWidget(self.white_king, 0, 1, 1, 1)
        self.black_king = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.black_king.setText("")
        self.black_king.setPixmap(QtGui.QPixmap("C:\\Users\\Mski\\Desktop\\ChessEye\\UI\\img/black_king.png"))
        self.black_king.setObjectName("black_king")
        self.piece_picker.addWidget(self.black_king, 0, 0, 1, 1)
        self.gridLayoutWidget = QtWidgets.QWidget(self.main_widget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(20, 10, 141, 111))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.board = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.board.setContentsMargins(0, 0, 0, 0)
        self.board.setObjectName("board")
        MainWindow.setCentralWidget(self.main_widget)
        
        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
